# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Creative Engineering
email: email@me.com
description: >
  Solving software and life with creative engineering
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://diwant.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Diwant Vaidya'
bio: >
  A software engineer for more than fifteen years, I find
  that every problem I solve helps me imagine new and innovative
  answers for questions I ponder about.  Sometimes, its just
  fun to wonder about the questions.
author_image: "/assets/images/author.jpg"
twitter_username: diwant
github_username:  diwant

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
